server:
  port: 3000
spring:
  application:
    name: redis-provider #当前服务名称，注册服务信息
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /yang
    username: root
    password: root
    template:
      exchange: RABBITMQ.YANG.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
      prefer-ip-address: true