server:
  port: 5000
spring:
  application:
    name: project-manager #当前服务名称，注册服务信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
      prefer-ip-address: true